# Generated by Django 5.1.7 on 2025-08-17 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_meeting_payment_amount_dentalservice_and_more'),
        ('app2', '0013_customerdebt_discount_procent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'Dori', 'verbose_name_plural': 'Dorilar'},
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='dosage',
        ),
        migrations.AddField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barkod'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='contraindications',
            field=models.TextField(blank=True, null=True, verbose_name='Kontrendikatsiyalar'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage_strength',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Doza kuchi'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage_unit',
            field=models.CharField(blank=True, choices=[('tablet', 'Tabletka'), ('ml', 'Millilitr'), ('mg', 'Milligramm'), ('g', 'Gramm'), ('piece', 'Dona'), ('bottle', 'Shisha'), ('ampoule', 'Ampula'), ('syringe', 'Shprits')], max_length=20, null=True, verbose_name="Doza o'lchov birligi"),
        ),
        migrations.AddField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Saqlash muddati'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Generik nomi'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ishlab chiqaruvchi'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Dori kodi'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=10, verbose_name='Minimal ombor'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sotuv narxi'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='side_effects',
            field=models.TextField(blank=True, null=True, verbose_name="Yon ta'sirlar"),
        ),
        migrations.AddField(
            model_name='medicine',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('discontinued', 'Ishlatilmaydi')], default='active', max_length=20, verbose_name='Holat'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Ombor miqdori'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bitta doza narxi'),
        ),
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_categories', to='app.clinic')),
            ],
            options={
                'verbose_name': 'Dori kategoriyasi',
                'verbose_name_plural': 'Dori kategoriyalari',
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='app2.medicinecategory', verbose_name='Kategoriya'),
        ),
        migrations.CreateModel(
            name='MedicinePrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription_date', models.DateField(verbose_name='Retsept sanasi')),
                ('diagnosis', models.CharField(max_length=255, verbose_name='Tashxis')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='app.customer', verbose_name='Bemor')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Shifokor')),
            ],
            options={
                'verbose_name': 'Retsept',
                'verbose_name_plural': 'Retseptlar',
            },
        ),
        migrations.CreateModel(
            name='MedicinePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.CharField(max_length=255, verbose_name='Yetkazib beruvchi')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bitta narxi')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Umumiy narx')),
                ('purchase_date', models.DateField(verbose_name='Sotib olish sanasi')),
                ('expiry_date', models.DateField(verbose_name='Saqlash muddati')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Faktura raqami')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='app2.medicine', verbose_name='Dori')),
                ('purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sotib olgan shaxs')),
            ],
            options={
                'verbose_name': 'Dori sotib olish',
                'verbose_name_plural': 'Dorilar sotib olish',
            },
        ),
        migrations.CreateModel(
            name='MedicineSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bitta narxi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Umumiy narx')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chegirma miqdori')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Chegirma foizi')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Yakuniy narx')),
                ('sale_type', models.CharField(choices=[('retail', 'Chakana sotuv'), ('wholesale', 'Ommaviy sotuv'), ('prescription', "Retsept bo'yicha")], default='retail', max_length=20, verbose_name='Sotuv turi')),
                ('prescription_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Retsept raqami')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_purchases', to='app.customer', verbose_name='Mijoz')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_sales', to=settings.AUTH_USER_MODEL, verbose_name='Shifokor')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='app2.medicine', verbose_name='Dori')),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_sales', to=settings.AUTH_USER_MODEL, verbose_name='Sotgan shaxs')),
            ],
            options={
                'verbose_name': 'Dori sotuv',
                'verbose_name_plural': 'Dorilar sotuv',
            },
        ),
        migrations.CreateModel(
            name='MedicineStockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_type', models.CharField(choices=[('addition', "Qo'shish"), ('subtraction', 'Ayirish'), ('correction', 'Tuzatish'), ('damage', 'Zarar'), ('expiry', "Muddati o'tgan")], max_length=20, verbose_name='Tuzatish turi')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('reason', models.CharField(max_length=255, verbose_name='Sabab')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('adjusted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tuzatgan shaxs')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='app2.medicine', verbose_name='Dori')),
            ],
            options={
                'verbose_name': 'Ombor tuzatish',
                'verbose_name_plural': 'Ombor tuzatishlar',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosage', models.CharField(max_length=100, verbose_name='Doza')),
                ('frequency', models.CharField(max_length=100, verbose_name='Qanday berish')),
                ('duration', models.CharField(max_length=100, verbose_name='Davomiyligi')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name="Ko'rsatmalar")),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.medicine', verbose_name='Dori')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app2.medicineprescription', verbose_name='Retsept')),
            ],
            options={
                'verbose_name': 'Retsept elementi',
                'verbose_name_plural': 'Retsept elementlari',
            },
        ),
    ]
