# Generated by Django 5.2.16 on 2026-07-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0014_alter_medicine_options_remove_medicine_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='supplier_firm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yetkazib beruvchi firma'),
        ),
    ]
