# Generated by Django 5.2.16 on 2026-07-17 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_user_specialization'),
        ('app2', '0015_medicine_supplier_firm'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Firma nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_firms', to='app.clinic')),
            ],
            options={
                'verbose_name': 'Dori firmasi',
                'verbose_name_plural': 'Dori firmalari',
            },
        ),
    ]
