# Generated by Django 5.2.16 on 2026-08-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0016_medicinefirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdebt',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='customerdebt',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
