# Generated by Django 5.1.7 on 2025-08-17 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_user_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicnotification',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer', verbose_name='Bemor'),
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AlterField(
            model_name='clinicnotification',
            name='status',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('admin', 'Admin'), ('director', 'Director'), ('admin_director', 'Admin and Director'), ('customer', 'Customer')], default='admin_director', max_length=20),
        ),
    ]
