# Generated by Django 5.2.16 on 2026-07-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_clinicnotification_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='floors',
            field=models.PositiveIntegerField(default=1, help_text='Filialdagi qavatlar soni'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bemor kelgan vaqt'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qabul tugagan vaqt'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qabul boshlangan vaqt'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed',
            field=models.BooleanField(default=True, help_text="Foydalanuvchi vaqtinchalik parolni o'zgartirganmi"),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
