# Generated by Django 5.2.16 on 2026-07-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_branch_floors_meeting_arrived_at_meeting_finished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_type',
            field=models.CharField(choices=[('salary', 'Oylik'), ('kpi', 'KPI'), ('salary_kpi', 'Oylik + KPI'), ('trainee', "Ish o'rganuvchi")], default='salary', help_text="Xodim qanday asosda ishlaydi: oylik, KPI, ikkalasi yoki ish o'rganuvchi", max_length=20),
        ),
    ]
