# Generated by Django 5.2.16 on 2026-07-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_customer_clinic_alter_customer_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('general', 'Umumiy stomatolog'), ('therapist', 'Terapevt stomatolog'), ('surgeon', 'Jarroh stomatolog'), ('orthodontist', 'Ortodont'), ('orthopedist', 'Ortoped (protezist)'), ('periodontist', 'Parodontolog'), ('endodontist', 'Endodont'), ('pediatric', 'Bolalar stomatologi'), ('implantologist', 'Implantolog'), ('hygienist', 'Gigienist'), ('director', 'Director'), ('stomatology', 'Stomatologiya'), ('other', 'Boshqa')], default='general', max_length=20, null=True),
        ),
    ]
