# Generated by Django 5.2.16 on 2026-08-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalservice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
